apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp-deployment
    app.kubernetes.io/version: "stable"
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: myapp-system
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  # admin:password
  auth: YWRtaW46JGFwcjEkOHdZVmU3czEkdndURGpuM1RGM2trUk9ydGFuMUVCMQo=
